# Generated by Django 2.1.3 on 2018-11-04 19:07

from django.db import migrations, models
import i18nfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', i18nfield.fields.I18nCharField(max_length=200, verbose_name='Title')),
            ],
        ),
    ]
